// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN9UPBKEODxzAeoiks_m5DROQZjZHLP-Q',
    appId: '1:302165367615:web:1cc3815f1b550ef9f4d18a',
    messagingSenderId: '302165367615',
    projectId: 'skin-cancer-detection-c3bd5',
    authDomain: 'skin-cancer-detection-c3bd5.firebaseapp.com',
    storageBucket: 'skin-cancer-detection-c3bd5.appspot.com',
    measurementId: 'G-SXDR87BDSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKQZRIm5yTXIIUo0h7AhHF7ogvjG9YAj4',
    appId: '1:302165367615:android:9462d7353e4e4d54f4d18a',
    messagingSenderId: '302165367615',
    projectId: 'skin-cancer-detection-c3bd5',
    storageBucket: 'skin-cancer-detection-c3bd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBmb2Mdltrfg0osltF5iTLBIW6YkiJ3D4',
    appId: '1:302165367615:ios:af50ca86bacb84d8f4d18a',
    messagingSenderId: '302165367615',
    projectId: 'skin-cancer-detection-c3bd5',
    storageBucket: 'skin-cancer-detection-c3bd5.appspot.com',
    iosBundleId: 'com.example.skinCancerDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBmb2Mdltrfg0osltF5iTLBIW6YkiJ3D4',
    appId: '1:302165367615:ios:3b70592afb6d63bbf4d18a',
    messagingSenderId: '302165367615',
    projectId: 'skin-cancer-detection-c3bd5',
    storageBucket: 'skin-cancer-detection-c3bd5.appspot.com',
    iosBundleId: 'com.example.skinCancerDetection.RunnerTests',
  );
}
